# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-paginate

# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that `some-other-jekyll-plugin` is not listed here. Therefore,
# it will not be loaded under safe mode.
whitelist:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-paginate


# Permalinks
permalink:        pretty

# Setup
title:            Jakub's Home Page
tagline:          
description:      > 
                  Jakub Nierostek's personal home page and blog concerning all things interesting. Built with <a href="http://jekyllrb.com" target="_blank">Jekyll</a>. Find the source code <a href="https://github.com/nierja/hyde" target="_blank">here</a>.
url:              https://www.jakubnierostek.cz/
baseurl:          /
# 'Personal home page and blog of Jakub Nierostek. Built with <a href="http://jekyllrb.com" target="_blank">Jekyll</a>. Find the source <a href="https://github.com/nierja/hyde" target="_blank">here</a>.'


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nierja

# Photo gallery
# defaults:
#   - scope:
#       path: "assets/imgages"
#     values:
#       image: true
